# Types of monitored events

INNER_OBJECT_CREATED            = 0x001
INNER_OBJECT_NAME_CHANGED       = 0x002
INNER_OBJECT_CONTENT_CHANGED    = 0x004
INNER_OBJECT_INCLUDED           = 0x008
INNER_OBJECT_EXCLUDED           = 0x010
INNER_OBJECT_DELETED            = 0x020
DIRECTORY_NAME_CHANGED          = 0x040
DIRECTORY_REPLACED              = 0x080
DIRECTORY_DELETED               = 0x100
